galaxy_info:
  author: Tom Gamull
  description: Install NGINX Plus
  company: NGINX

  license: license Apache 2.0
  min_ansible_version: 1.2

  platforms:
  - name: EL
    versions:
    - all
    - 5
    - 6
    - 7
  galaxy_tags: []
dependencies: []